post:
  summary: Create a new task
  requestBody:
    description: Task object that needs to be added
    required: true
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/task-input.yml'
  responses:
    201:
      description: Task created successfully
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/task.yml'
    400:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/error.yml'
