get:
  summary: Get all tasks
  responses:
    200:
      description: A list of tasks
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: '../../components/schemas/task.yml'
    400:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/error.yml'
