delete:
  summary: Delete a task
  operationId: deleteTask
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
  responses:
    '204':
      description: Task deleted successfully
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Task not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
