delete:
  summary: Delete a task
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: string
      description: Task ID
  responses:
    200:
      description: Task deleted successfully
    400:
      description: Invalid request
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/error.yml'
    404:
      description: Task not found
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/error.yml'
