put:
  summary: Update a task
  operationId: updateTask
  parameters:
    - name: id
      in: path
      required: true
      schema:
        type: string
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/TaskInput'
  responses:
    '200':
      description: Task updated successfully
      content:
        application/json:
          schema:
            $ref: '#/components/responses/TaskResponse'
    '400':
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: Task not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
