put:
  summary: Update an existing task
  parameters:
    - in: path
      name: id
      required: true
      schema:
        type: string
      description: Task ID
  requestBody:
    description: Task object that needs to be updated
    required: true
    content:
      application/json:
        schema:
          $ref: '../../components/schemas/task-input.yml'
  responses:
    200:
      description: Task updated successfully
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/task.yml'
    400:
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/error.yml'
    404:
      description: Task not found
      content:
        application/json:
          schema:
            $ref: '../../components/schemas/error.yml'
