version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "3010:3010"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/task-manager

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
