openapi: 3.0.3
info:
  title: Task Manager API
  description: API documentation for the Task Manager application.
  version: 1.0.0
servers:
  - url: http://localhost:3010
paths:
  /tasks:
    get:
      $ref: 'paths/tasks/get-all.yml'
    post:
      $ref: 'paths/tasks/create.yml'
  /tasks/{id}:
    put:
      $ref: 'paths/tasks/update.yml'
    delete:
      $ref: 'paths/tasks/remove.yml'
components:
  schemas:
    Task:
      $ref: 'components/schemas/task.yml'
    TaskInput:
      $ref: 'components/schemas/task-input.yml'
    Error:
      $ref: 'components/schemas/errors.yml'
  responses:
    GetAllTasksResponse:
      $ref: 'components/responses/get-all.yml'
    TaskResponse:
      $ref: 'components/responses/task.yml'
